-- 1.What is the total revenue generated by male vs. female customers?

SELECT 
    gender, SUM(purchase_amount) AS total_revenue
FROM
    customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT 
    customer_id, purchase_amount
FROM
    customer
WHERE
    discount_applied = 'Yes'
        AND purchase_amount >= (SELECT 
            AVG(purchase_amount)
        FROM
            customer);

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS 'Average Product Rating'
FROM
    customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT 
    shipping_type, AVG(purchase_amount)
FROM
    customer
WHERE
    shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.

SELECT 
    subscription_status,
    COUNT(customer_id),
    SUM(purchase_amount) AS total_revenue,
    AVG(purchase_amount) AS avg_spend
FROM
    customer
GROUP BY subscription_status
ORDER BY total_revenue , avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT 
    item_purchased,
    ROUND(100.0 * SUM(CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END) / COUNT(*),
            2) AS discount_rate
FROM
    customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as(
select customer_id,previous_purchases,
case
when previous_purchases=1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'loyal'
end as segment_customer
from customer
)
select segment_customer,count(*) as 'number of customer'
from customer_type
group by segment_customer;

-- Q8. What are the top 3 most purchased products within each category? 

with item_count as(
select item_purchased,category,
count(customer_id) as total_orders,
row_number() over (Partition by category order by count(customer_id) desc) as item_rank
from customer
group by item_purchased,category
)
select item_rank,item_purchased,total_orders
from item_count
where item_rank<=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?

SELECT 
    age_group, SUM(purchase_amount) AS revenue
FROM
    customer
GROUP BY age_group
ORDER BY revenue DESC;
